apiVersion: batch/v1
kind: Job
metadata:
  name: bwh-demo-loop-job
spec:
  template:
    spec:
      containers:
      - name: alpine-ping
        image: alpine:3.13.2
        command: ["ping","8.8.8.8"]
      restartPolicy: Never
  backoffLimit: 4