apiVersion: apps/v1
kind: Deployment
metadata:
  name: bwh-demo-bb-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bb-web
  template:
    metadata:
      labels:
        app: bb-web
    spec:
      containers:
      - name: bb-site
        image: bulletinboard/bulletinboard:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: bwh-demo-bb-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: bb-web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001